version: '3.9'

services:
  db:
    image: mysql:8.0.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - backend
  api:
    image: api-videos-gallery
    build: 
        dockerfile: Dockerfile
        context: ./api
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - 3001:3001
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
  web:
    image: web-videos-gallery
    build: 
        dockerfile: Dockerfile
        context: ./web
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - api
    ports:
      - 3000:3000
networks:
  backend:
    driver: bridge
volumes:
  my-db:


